services:
  - type: web
    name: yt-summarizer
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.cjs
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: 10000
